kind: Service
apiVersion: v1
metadata:
  name: bookstore-mongo1-service1
spec:
  selector:
    app: bookstore-mongo1-service1
  ports:
  - protocol: TCP
    port: 8081
    nodePort: 30072
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookstore-mongo1-service1
spec:
  selector:
      matchLabels:
        app: bookstore-mongo1-service1
  replicas: 1
  template:
    metadata:
      labels:
        app: bookstore-mongo1-service1
    spec:
      containers:
        - name: bookstore-mongo1-service1
          image: veerareddyt/bookstore:1.2
          imagePullPolicy: Always
          ports:
          - containerPort: 8081
          env:
            - name: MONGO_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: username
            - name: MONGO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: password
            - name: MONGO_DB
              valueFrom:
                configMapKeyRef:
                  name: mongo-conf  
                  key: database
            - name: MONGO_HOST
              valueFrom:
                configMapKeyRef:
                  name: mongo-conf 
                  key: host
                  
